### ISSUE TITLE
AITL Loss

### ISSUE THREAD

**Issue by Chaucergit** [yuange250/Video-based-person-ReID-with-Attribute-information#2]
what the means of attr_lens = [[5, 6, 2, 2, 2, 2, 2, 2, 2], [ 9, 10, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2]]?

**Comment by yuange250** [comment]
其实就是

**Comment by yuange250** [comment]
> what the means of attr_lens = [[5, 6, 2, 2, 2, 2, 2, 2, 2], [ 9, 10, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2]]?

The length  of each single attribute, i split the attributes of MARS into two groups, id-irrelevant or id-relevant, which corresponds to the two arrays. And each group contains several attributes, each number in the array represents the maximal-classifications  of each attribute. For example, the first 5 in attr_lens[0] means there is 5 classifications in id-irrelevant attribute "Motion" (working, standing, runing, biking and others). 

----
就是不同属性的分类数，主要用来构建属性分类器的，一开始我是每种属性创建一个分类器，所以要把每种属性的分类种类列出来，比如第一个array里的第一个元素5，表示motion这个属性有五个分类(working, standing, runing, biking and others)，之所以分成两个数组是因为我把属性分为了身份相关和身份无关属性，第一个数组是身份无关属性，有9个身份无关属性，每个数字分别代表每个属性的分类数量。具体每个数字对应哪个分类可以把属性标签拿下来看一下哈
