### ISSUE TITLE
The attribute label is lost

### ISSUE THREAD

**Issue by jackie840129** [yuange250/Video-based-person-ReID-with-Attribute-information#3]
Hi @yuange250 
The download link of the attribute label in the project page is lost. (http://irip.buaa.edu.cn/mars_duke_attributes/index.html) 
Can you share the data to me~?
Thank you very much!

**Comment by yuange250** [comment]
good luck~













At 2020-08-12 13:25:23, "Chih-Ting Liu (劉致廷)" <notifications@github.com> wrote:

Hi @yuange250
The download link of the attribute label in the project page is lost. (http://irip.buaa.edu.cn/mars_duke_attributes/index.html)
Can you share the data to me~?
Thank you very much!

**Comment by yuange250** [comment]
> Hi @yuange250
> The download link of the attribute label in the project page is lost. (http://irip.buaa.edu.cn/mars_duke_attributes/index.html)
> Can you share the data to me~?
> Thank you very much!

**Comment by yuange250** [comment]
> Hi @yuange250
> The download link of the attribute label in the project page is lost. (http://irip.buaa.edu.cn/mars_duke_attributes/index.html)
> Can you share the data to me~?
> Thank you very much!

url : https://pan.baidu.com/share/init?surl=vSwoqM9s1ImKzRZHDlmpWQ
passwd : beda

**Comment by jackie840129** [comment]
Hi @yuange250  
Because I cannot create a baidu account, could you send the two csv files to me through email?
Please~ Thank you!
