### ISSUE TITLE
mAP=0.7%？？？

### ISSUE THREAD

**Issue by SaraXuBing** [yuange250/Video-based-person-ReID-with-Attribute-information#4]
I trained the net twice, but the map just 0.7%? Why?
![image](https://user-images.githubusercontent.com/49355909/98623352-74408380-2346-11eb-8834-9f38d41c3c7a.png)

**Comment by yuange250** [comment]
is apex installed ?

**Comment by SaraXuBing** [comment]
yes，I Installed apex 
![image](https://user-images.githubusercontent.com/49355909/98654893-d36bbb80-2379-11eb-9fcc-fe2dccb1485e.png)

**Comment by SaraXuBing** [comment]
I have used MARS and DukeMTMC-VideoReID datasats，but the results are both mAP = 0.7%, And I just run the main_baseline.py, do I need to change some code?

**Comment by yuange250** [comment]
Try reducing batch_size and use single card

**Comment by yuange250** [comment]
Is Duke fail like this？or just mars？

**Comment by SaraXuBing** [comment]
both of them

**Comment by SaraXuBing** [comment]
Thank you, I will do it as you just say, and then I will tell you the result

**Comment by yuange250** [comment]
好的，加油～

**Comment by SaraXuBing** [comment]
Apex没有编译成功能不能训练网络？我之前编译的差一点，没有编译完全

**Comment by yuange250** [comment]
> Apex没有编译成功能不能训练网络？我之前编译的差一点，没有编译完全

把相关的apex注释掉吧，会差点，不过不会差太多
