### ISSUE TITLE
一些问题希望请教（因为都是中国人所以不想用英文提问了hhh）

### ISSUE THREAD

**Issue by Messagel** [yuange250/Video-based-person-ReID-with-Attribute-information#5]
您好，我想请教您的问题是有关显存大小问题，在视频行人重识别领域如果使用较小的batch，是否注定是无法复现像近年工作中一些采样256、512张图像的那种在MARS上R1精度高达90的任务的。因为我看您的文章中写出的结果精度比较中肯，并没有用非常大的显存来提高batch size。我平时在做实验的时候因为显存不够（只有单卡）所以常常因为精度问题感到苦恼，觉得很困扰，是否batch size是目前一些SOTA精度高的原因呢？这个问题令我很困惑，期待您的解答。

**Comment by yuange250** [comment]
> 您好，我想请教您的问题是有关显存大小问题，在视频行人重识别领域如果使用较小的batch，是否注定是无法复现像近年工作中一些采样256、512张图像的那种在MARS上R1精度高达90的任务的。因为我看您的文章中写出的结果精度比较中肯，并没有用非常大的显存来提高batch size。我平时在做实验的时候因为显存不够（只有单卡）所以常常因为精度问题感到苦恼，觉得很困扰，是否batch size是目前一些SOTA精度高的原因呢？这个问题令我很困惑，期待您的解答。

确实如此，一定范围内增大batch size对softmax和triplet确实都有很大的增益，很多sota不开源也是因为使用纯粹类似增大batch这种trick提升精度，然后再用自己提出的概念进行封装

**Comment by Messagel** [comment]
> > 您好，我想请教您的问题是有关显存大小问题，在视频行人重识别领域如果使用较小的batch，是否注定是无法复现像近年工作中一些采样256、512张图像的那种在MARS上R1精度高达90的任务的。因为我看您的文章中写出的结果精度比较中肯，并没有用非常大的显存来提高batch size。我平时在做实验的时候因为显存不够（只有单卡）所以常常因为精度问题感到苦恼，觉得很困扰，是否batch size是目前一些SOTA精度高的原因呢？这个问题令我很困惑，期待您的解答。
> 
> 确实如此，一定范围内增大batch size对softmax和triplet确实都有很大的增益，很多sota不开源也是因为使用纯粹类似增大batch这种trick提升精度，然后再用自己提出的概念进行封装

感谢回复，明白了。
